name: Print Software Versions
on: 
  push: 
      branches: main
jobs: 
  printSoftwareVersions:
    runs-on: ubuntu-latest
    steps:
          - name: Print Python Version
            run: python --version
  printDatabaseVersions:
    runs-on: ubuntu-latest
    steps:
        - name: Print MySQL Version
          run: mysql --version
