name: Print Software Versions
on: 
  push: 
      branches: main
jobs: 
  printSoftwareVersions:
    runs-on: ubuntu-latest
    steps:
          - name: Print Node Version
            run: node --version
  printDatabaseVersions:
    runs-on: ubuntu-latest
    steps:
        - name: Print PostgreSQL Version
          run: postgresql --version
